services:
  - type: web
    name: elp-backend
    runtime: node
    rootDir: server
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npx prisma db push && npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 15m
      - key: JWT_REFRESH_EXPIRES_IN
        value: 7d
      - key: GROQ_API_KEY
        sync: false
      - key: CLIENT_URL
        sync: false
      - key: PORT
        value: 3001
